"""empty message

Revision ID: 0b8018d845b1
Revises: 
Create Date: 2022-07-23 14:33:48.551226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8018d845b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.add_column('users', sa.Column('profile_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'images', ['profile_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_image_id')
    op.drop_table('images')
    # ### end Alembic commands ###
