"""empty message

Revision ID: 3e73eb5f9076
Revises: ef0829df7e6d
Create Date: 2022-07-23 16:47:31.714478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e73eb5f9076'
down_revision = 'ef0829df7e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friend_requests', ['sending_user_id', 'receiving_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend_requests', type_='unique')
    # ### end Alembic commands ###
